server:
    port: 8080
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/logiston
        username: postgres
        password: 1111
        tomcat:
            max-active: 50
            max-idle: 20
            max-wait: 20000
            min-idle: 15
    jpa:
        database: POSTGRESQL
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                enable_lazy_load_no_trans: true
                format_sql: true
                id:
                    new_generator_mappings: false
        show-sql: false
    queries:
        roles-query: select users.email, role.role from users inner join user_role on(users.user_id = user_role.user_id) inner join role on(user_role.role_id = role.role_id) where users.email = ?
        user-query: select users.email, users.password, users.active from users where users.email = ?
    thymeleaf:
        cache: false
logging:
    level:
        org:
            hibernate:
                SQL: 'off'
                type:
                    descriptor:
                        sql:
                            BasicBinder: 'off'
